### ISSUE TITLE
\paragraph{} headings are not indented

### ISSUE THREAD

**Issue by gridaphobe** [stevecheckoway/ucsddissertation#1]
Apparently they need to be indented just like regular paragraphs, which you can accomplish with

```
\titleformat\paragraph[runin]{\normalfont\normalsize\bfseries}
        {\theparagraph}{1em}{\indent}
```

though I ended up preferring to set them as a header on their own line

```
\titleformat\paragraph{\sectioningformatting\normalsize\bfseries}
	{\theparagraph}{1em}{}
```

since I don't use `subsubsection`s.

Just FYI, thanks for the great template!

**Comment by stevecheckoway** [comment]
Did the requirements change? My [dissertation](https://www.cs.uic.edu/~s/papers/dissertation/dissertation.pdf) definitely uses `\paragraph` that adds vertical space but does not indent.

**Comment by gridaphobe** [comment]
I don't think they changed, it just says that all paragraphs must be indented 0.5". And I was just told yesterday at the prelim that the following formatting was not ok.

<img width="274" alt="not-ok" src="https://user-images.githubusercontent.com/201997/28371257-5a7e68a2-6c94-11e7-95e3-75f2d24bef63.png">

They suggested either indenting the heading too, or setting it on its own line, which is what I decided to do.

<img width="269" alt="ok" src="https://user-images.githubusercontent.com/201997/28371156-1a48e794-6c94-11e7-8a2d-f4708631a6e9.png">

**Comment by arjunroy** [comment]
As an addendum, OGS told me literally the same thing today.

Unlike Eric who is smart, I just hacked it by adding an empty \mbox{} after every \paragraph{blah}.

**Comment by stevecheckoway** [comment]
Sorry for taking so long. I had forgotten about this until I saw Arjun's PR a few minutes ago. https://github.com/stevecheckoway/ucsddissertation/commit/62a8add8023f16b6dc8d9a53909beba63803cf41 changed the formatting of `\paragraph` to be almost the same as `\subsubsection` except that there's no additional space between the paragraph heading and the text.

**Comment by gridaphobe** [comment]
> Unlike Eric who is smart...

😕

**Comment by Ptival** [comment]
I was told the same thing, and ended up doing this:

```
\setlength\parindent{0.5in}
```

I don't know if this is a good idea, I might end up stealing @gridaphobe 's hack.

**Comment by stevecheckoway** [comment]
@Ptival I'm not sure I follow. That's already there. https://github.com/stevecheckoway/ucsddissertation/blob/master/ucsddissertation.cls#L213

**Comment by Ptival** [comment]
Oh, I might have a different problem then... Maybe one of my packages overrides this. Nevermind!

**Comment by stevecheckoway** [comment]
Has this been fixed to everyone's satisfaction?
