### ISSUE TITLE
List of custom float

### ISSUE THREAD

**Issue by blowfish880** [stevecheckoway/ucsddissertation#2]
For my algorithms I use a custom float:

```
\floatstyle{ruled}
\newfloat{algorithm}{H}{lop}[chapter]
\floatname{algorithm}{Algorithm}
```
Now I want to include a list of algorithms but I can't figure out how to do this. Simply using `\listof{algorithm}{List of Algorithms}` does insert a list, but it's formatted differently from the list of figures and tables.

**Comment by stevecheckoway** [comment]
The class already has support for the `algorithm` package.

```
\usepackage[ruled,chapter]{algorithm}
\floatplacement{algorithm}{H}
```

should work exactly as yours does (including making `H` the default float placement) except the file extension is `.loa` instead of `.lop`.

**Comment by blowfish880** [comment]
Works perfectly. Thank you!

**Comment by stevecheckoway** [comment]
Great. Glad I could help.
