### ISSUE TITLE
Bad display of Appendix in Table of Contents

### ISSUE THREAD

**Issue by Ptival** [stevecheckoway/ucsddissertation#4]
![image](https://user-images.githubusercontent.com/478606/47260635-19444700-d474-11e8-9d63-279bcd4cf1cf.png)

I'm not sure whether this is part of what I have done, but the table of contents does not put enough space for the text "Appendix A".

**Comment by stevecheckoway** [comment]
The example has an appendix in the table of contents and there's enough space added. What is the contents of the `\chapter{...}` that causes that?

**Comment by Ptival** [comment]
This happens to me:

https://www.overleaf.com/3628336433nqkdfdwmbmhp

And if you uncomment the `\overfullrule`, it gets worse.

Note: I am using xelatex, if that's relevant.

[EDIT] Oh I guess the `\overfullrule` just displays black boxes when things get too bad?

**Comment by Ptival** [comment]
I also seem to get the same problem with the example:

![image](https://user-images.githubusercontent.com/478606/47323341-37df4500-d610-11e8-82b7-e785ffed9b30.png)

[EDIT] Indeed, with pdflatex things aren't too bad, but with xelatex, the black boxes appear... :-(

**Comment by stevecheckoway** [comment]
`\overfullrull` adds a box of the specified width when an hbox is too full and it's typesetting outside the width of the box. So that's definitely the cause of the black box.

The issue appears to be that xelatex is causing different fonts to be used.

Here's `xelatex`.
```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
SCROQA+LMRoman12-Regular-Identity-H  CID Type 0C       Identity-H       yes yes yes      5  0
CFTXKN+LMRoman17-Regular-Identity-H  CID Type 0C       Identity-H       yes yes yes     80  0
WKYKRU+LMMono12-Regular-Identity-H   CID Type 0C       Identity-H       yes yes yes     82  0
```

And here's `pdflatex`:
```
name                                 type              encoding         emb sub uni object ID
------------------------------------ ----------------- ---------------- --- --- --- ---------
RODPZS+NimbusRomNo9L-Regu            Type 1            Custom           yes yes no     120  0
CUBZJJ+NimbusRomNo9L-ReguItal        Type 1            Custom           yes yes no     139  0
WKYLPU+NimbusRomNo9L-Medi            Type 1            Custom           yes yes no     219  0
AXXZNB+CMTT12                        Type 1            Builtin          yes yes no     220  0
YZWWLN+CMSY10                        Type 1            Builtin          yes yes no     280  0
```

So Latin modern for xelatex vs. Nimbus Roman and Computer Modern for pdflatex.

This changes the spacing enough to get an overfull rule, apparently.

**Comment by stevecheckoway** [comment]
https://github.com/stevecheckoway/ucsddissertation/commit/f4526440d09d4f683cca47eed68d2452106c1a0c should fix the problem (at least it does with the example) by increasing the space. If you're still having problems, reopen the bug.

**Comment by stevecheckoway** [comment]
Give https://github.com/stevecheckoway/ucsddissertation/commit/2a6aed7606e545d3a4ca5aad14e7d94e3bf28e6f a shot.

**Comment by Ptival** [comment]
This one seems to solve the initial issue, and everything seems named appropriately. Thanks!

**Comment by stevecheckoway** [comment]
Awesome! Thanks for bringing this to my attention. (And sorry for the misfix earlier.)
